- hosts: all
  tasks:
  - yum_repository:
      name: Docker
      description: Docker Repo
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
      gpgcheck: no

  - package:
      name: "docker-ce-18.09.1-3.el7.x86_64"
      state: present

  - service:
      name: "docker"
      state: started
      enabled: yes

  - pip:
      name: docker
      executable: pip3

  - copy:
      src: "/Ansible/index.html"
      dest: "/var/www/html"

  - docker_container:
      name: MyWebServer
      image: httpd
      state: started
      exposed_ports: "80"
      ports: "8888:80"
      volumes: /var/www/html:/usr/local/apache2/htdocs/
